global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'metabase'
    static_configs:
      - targets: ['metabase:3300']
  
  - job_name: 'jmx'
    static_configs:
      - targets: ['metabase:3301']
  # - job_name: 'tempo'
  #   static_configs:
  #     - targets: [ 'tempo:3200' ]
  
  # - job_name: 'loki'
  #   static_configs:
  #     - targets: [ 'loki:3100' ]